# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controlTheoryPowellPowell.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1049, 863)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblProgramTitle = QtWidgets.QLabel(self.frame)
        self.lblProgramTitle.setObjectName("lblProgramTitle")
        self.verticalLayout_2.addWidget(self.lblProgramTitle)
        self.frameFunctionDetails = QtWidgets.QFrame(self.frame)
        self.frameFunctionDetails.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFunctionDetails.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFunctionDetails.setObjectName("frameFunctionDetails")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frameFunctionDetails)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalFrame = QtWidgets.QFrame(self.frameFunctionDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalFrame.sizePolicy().hasHeightForWidth())
        self.verticalFrame.setSizePolicy(sizePolicy)
        self.verticalFrame.setObjectName("verticalFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.verticalFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblObjFunc = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblObjFunc.sizePolicy().hasHeightForWidth())
        self.lblObjFunc.setSizePolicy(sizePolicy)
        self.lblObjFunc.setObjectName("lblObjFunc")
        self.gridLayout_3.addWidget(self.lblObjFunc, 0, 1, 1, 1)
        self.cmbObjFun = QtWidgets.QComboBox(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbObjFun.sizePolicy().hasHeightForWidth())
        self.cmbObjFun.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cmbObjFun.setFont(font)
        self.cmbObjFun.setEditable(True)
        self.cmbObjFun.setObjectName("cmbObjFun")
        self.cmbObjFun.addItem("")
        self.cmbObjFun.addItem("")
        self.cmbObjFun.addItem("")
        self.gridLayout_3.addWidget(self.cmbObjFun, 1, 1, 1, 1)
        self.lblfx = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblfx.sizePolicy().hasHeightForWidth())
        self.lblfx.setSizePolicy(sizePolicy)
        self.lblfx.setObjectName("lblfx")
        self.gridLayout_3.addWidget(self.lblfx, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.verticalFrame, 0, 2, 1, 1)
        self.frmFunDetails = QtWidgets.QFrame(self.frameFunctionDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmFunDetails.sizePolicy().hasHeightForWidth())
        self.frmFunDetails.setSizePolicy(sizePolicy)
        self.frmFunDetails.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmFunDetails.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmFunDetails.setObjectName("frmFunDetails")
        self.gridLayout = QtWidgets.QGridLayout(self.frmFunDetails)
        self.gridLayout.setObjectName("gridLayout")
        self.lblVariables = QtWidgets.QLabel(self.frmFunDetails)
        self.lblVariables.setObjectName("lblVariables")
        self.gridLayout.addWidget(self.lblVariables, 0, 0, 1, 1)
        self.cmbVariables = QtWidgets.QComboBox(self.frmFunDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbVariables.sizePolicy().hasHeightForWidth())
        self.cmbVariables.setSizePolicy(sizePolicy)
        self.cmbVariables.setObjectName("cmbVariables")
        self.cmbVariables.addItem("")
        self.cmbVariables.addItem("")
        self.cmbVariables.addItem("")
        self.cmbVariables.addItem("")
        self.cmbVariables.addItem("")
        self.gridLayout.addWidget(self.cmbVariables, 0, 1, 1, 1)
        self.lblConstraints = QtWidgets.QLabel(self.frmFunDetails)
        self.lblConstraints.setObjectName("lblConstraints")
        self.gridLayout.addWidget(self.lblConstraints, 1, 0, 1, 1)
        self.cmbConstraints = QtWidgets.QComboBox(self.frmFunDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbConstraints.sizePolicy().hasHeightForWidth())
        self.cmbConstraints.setSizePolicy(sizePolicy)
        self.cmbConstraints.setObjectName("cmbConstraints")
        self.cmbConstraints.addItem("")
        self.cmbConstraints.addItem("")
        self.cmbConstraints.addItem("")
        self.cmbConstraints.addItem("")
        self.cmbConstraints.addItem("")
        self.cmbConstraints.addItem("")
        self.gridLayout.addWidget(self.cmbConstraints, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frmFunDetails, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frameFunctionDetails)
        self.verticalLayout_3.addWidget(self.frame)
        self.tabBox = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabBox.sizePolicy().hasHeightForWidth())
        self.tabBox.setSizePolicy(sizePolicy)
        self.tabBox.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabBox.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabBox.setElideMode(QtCore.Qt.ElideLeft)
        self.tabBox.setObjectName("tabBox")
        self.tabParameters = QtWidgets.QWidget()
        self.tabParameters.setObjectName("tabParameters")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabParameters)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_6 = QtWidgets.QFrame(self.tabParameters)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setLineWidth(2)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.frame_3 = QtWidgets.QFrame(self.frame_6)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lblMaxIterations = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMaxIterations.sizePolicy().hasHeightForWidth())
        self.lblMaxIterations.setSizePolicy(sizePolicy)
        self.lblMaxIterations.setObjectName("lblMaxIterations")
        self.gridLayout_6.addWidget(self.lblMaxIterations, 0, 0, 1, 1)
        self.cmbMaxIterations = QtWidgets.QComboBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.cmbMaxIterations.sizePolicy().hasHeightForWidth())
        self.cmbMaxIterations.setSizePolicy(sizePolicy)
        self.cmbMaxIterations.setMinimumSize(QtCore.QSize(0, 15))
        self.cmbMaxIterations.setEditable(True)
        self.cmbMaxIterations.setObjectName("cmbMaxIterations")
        self.cmbMaxIterations.addItem("")
        self.cmbMaxIterations.addItem("")
        self.cmbMaxIterations.addItem("")
        self.cmbMaxIterations.addItem("")
        self.cmbMaxIterations.addItem("")
        self.cmbMaxIterations.addItem("")
        self.gridLayout_6.addWidget(self.cmbMaxIterations, 0, 1, 1, 1)
        self.cmbPowellEpsilon = QtWidgets.QComboBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.cmbPowellEpsilon.sizePolicy().hasHeightForWidth())
        self.cmbPowellEpsilon.setSizePolicy(sizePolicy)
        self.cmbPowellEpsilon.setMinimumSize(QtCore.QSize(0, 15))
        self.cmbPowellEpsilon.setEditable(True)
        self.cmbPowellEpsilon.setObjectName("cmbPowellEpsilon")
        self.cmbPowellEpsilon.addItem("")
        self.cmbPowellEpsilon.addItem("")
        self.cmbPowellEpsilon.addItem("")
        self.cmbPowellEpsilon.addItem("")
        self.cmbPowellEpsilon.addItem("")
        self.cmbPowellEpsilon.addItem("")
        self.cmbPowellEpsilon.addItem("")
        self.gridLayout_6.addWidget(self.cmbPowellEpsilon, 1, 1, 1, 1)
        self.lblEpsilon = QtWidgets.QLabel(self.frame_3)
        self.lblEpsilon.setObjectName("lblEpsilon")
        self.gridLayout_6.addWidget(self.lblEpsilon, 1, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_3)
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 0, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_3.setEditable(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_7.addWidget(self.comboBox_3, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 1, 0, 2, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_4.setEditable(True)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_7.addWidget(self.comboBox_4, 1, 1, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_5.setEditable(True)
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout_7.addWidget(self.comboBox_5, 2, 1, 2, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 3, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_7)
        self.gridLayout_9.addWidget(self.frame_6, 1, 0, 1, 1)
        self.gbStartPoint = QtWidgets.QGroupBox(self.tabParameters)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gbStartPoint.setFont(font)
        self.gbStartPoint.setFlat(False)
        self.gbStartPoint.setCheckable(False)
        self.gbStartPoint.setObjectName("gbStartPoint")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gbStartPoint)
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lbX0_2 = QtWidgets.QLabel(self.gbStartPoint)
        self.lbX0_2.setObjectName("lbX0_2")
        self.gridLayout_5.addWidget(self.lbX0_2, 2, 0, 1, 1)
        self.lbX0_1 = QtWidgets.QLabel(self.gbStartPoint)
        self.lbX0_1.setObjectName("lbX0_1")
        self.gridLayout_5.addWidget(self.lbX0_1, 0, 0, 1, 1)
        self.lbX0_4 = QtWidgets.QLabel(self.gbStartPoint)
        self.lbX0_4.setObjectName("lbX0_4")
        self.gridLayout_5.addWidget(self.lbX0_4, 4, 0, 1, 1)
        self.lbX0_3 = QtWidgets.QLabel(self.gbStartPoint)
        self.lbX0_3.setObjectName("lbX0_3")
        self.gridLayout_5.addWidget(self.lbX0_3, 3, 0, 1, 1)
        self.lbX0_5 = QtWidgets.QLabel(self.gbStartPoint)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbX0_5.sizePolicy().hasHeightForWidth())
        self.lbX0_5.setSizePolicy(sizePolicy)
        self.lbX0_5.setObjectName("lbX0_5")
        self.gridLayout_5.addWidget(self.lbX0_5, 5, 0, 1, 1)
        self.inputX0_1 = QtWidgets.QLineEdit(self.gbStartPoint)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputX0_1.setFont(font)
        self.inputX0_1.setObjectName("inputX0_1")
        self.gridLayout_5.addWidget(self.inputX0_1, 0, 1, 1, 1)
        self.inputX0_2 = QtWidgets.QLineEdit(self.gbStartPoint)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputX0_2.setFont(font)
        self.inputX0_2.setObjectName("inputX0_2")
        self.gridLayout_5.addWidget(self.inputX0_2, 2, 1, 1, 1)
        self.inputX0_3 = QtWidgets.QLineEdit(self.gbStartPoint)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputX0_3.setFont(font)
        self.inputX0_3.setObjectName("inputX0_3")
        self.gridLayout_5.addWidget(self.inputX0_3, 3, 1, 1, 1)
        self.inputX0_4 = QtWidgets.QLineEdit(self.gbStartPoint)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputX0_4.setFont(font)
        self.inputX0_4.setObjectName("inputX0_4")
        self.gridLayout_5.addWidget(self.inputX0_4, 4, 1, 1, 1)
        self.inputX0_5 = QtWidgets.QLineEdit(self.gbStartPoint)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputX0_5.setFont(font)
        self.inputX0_5.setObjectName("inputX0_5")
        self.gridLayout_5.addWidget(self.inputX0_5, 5, 1, 1, 1)
        self.gridLayout_9.addWidget(self.gbStartPoint, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem1, 1, 1, 1, 1)
        self.groupBoxConstraints = QtWidgets.QGroupBox(self.tabParameters)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxConstraints.setFont(font)
        self.groupBoxConstraints.setObjectName("groupBoxConstraints")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBoxConstraints)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblConstraint5 = QtWidgets.QLabel(self.groupBoxConstraints)
        self.lblConstraint5.setObjectName("lblConstraint5")
        self.gridLayout_4.addWidget(self.lblConstraint5, 4, 0, 1, 1)
        self.lblConstraint4 = QtWidgets.QLabel(self.groupBoxConstraints)
        self.lblConstraint4.setObjectName("lblConstraint4")
        self.gridLayout_4.addWidget(self.lblConstraint4, 3, 0, 1, 1)
        self.lblConstraint1 = QtWidgets.QLabel(self.groupBoxConstraints)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblConstraint1.sizePolicy().hasHeightForWidth())
        self.lblConstraint1.setSizePolicy(sizePolicy)
        self.lblConstraint1.setObjectName("lblConstraint1")
        self.gridLayout_4.addWidget(self.lblConstraint1, 0, 0, 1, 1)
        self.lblConstraint2 = QtWidgets.QLabel(self.groupBoxConstraints)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblConstraint2.sizePolicy().hasHeightForWidth())
        self.lblConstraint2.setSizePolicy(sizePolicy)
        self.lblConstraint2.setObjectName("lblConstraint2")
        self.gridLayout_4.addWidget(self.lblConstraint2, 1, 0, 1, 1)
        self.inputConstraint1 = QtWidgets.QLineEdit(self.groupBoxConstraints)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputConstraint1.setFont(font)
        self.inputConstraint1.setObjectName("inputConstraint1")
        self.gridLayout_4.addWidget(self.inputConstraint1, 0, 1, 1, 1)
        self.lblConstraint3 = QtWidgets.QLabel(self.groupBoxConstraints)
        self.lblConstraint3.setObjectName("lblConstraint3")
        self.gridLayout_4.addWidget(self.lblConstraint3, 2, 0, 1, 1)
        self.inputConstraint3 = QtWidgets.QLineEdit(self.groupBoxConstraints)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputConstraint3.setFont(font)
        self.inputConstraint3.setObjectName("inputConstraint3")
        self.gridLayout_4.addWidget(self.inputConstraint3, 2, 1, 1, 1)
        self.inputConstraint2 = QtWidgets.QLineEdit(self.groupBoxConstraints)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputConstraint2.setFont(font)
        self.inputConstraint2.setObjectName("inputConstraint2")
        self.gridLayout_4.addWidget(self.inputConstraint2, 1, 1, 1, 1)
        self.inputConstraint5 = QtWidgets.QLineEdit(self.groupBoxConstraints)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputConstraint5.setFont(font)
        self.inputConstraint5.setObjectName("inputConstraint5")
        self.gridLayout_4.addWidget(self.inputConstraint5, 4, 1, 1, 1)
        self.inputConstraint4 = QtWidgets.QLineEdit(self.groupBoxConstraints)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputConstraint4.setFont(font)
        self.inputConstraint4.setObjectName("inputConstraint4")
        self.gridLayout_4.addWidget(self.inputConstraint4, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBoxConstraints)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBoxConstraints)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBoxConstraints)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBoxConstraints)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 3, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBoxConstraints)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 4, 2, 1, 1)
        self.gridLayout_9.addWidget(self.groupBoxConstraints, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_9)
        self.frameParamRight = QtWidgets.QFrame(self.tabParameters)
        self.frameParamRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameParamRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameParamRight.setObjectName("frameParamRight")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameParamRight)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frameParamRight)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btnSearch = QtWidgets.QPushButton(self.frame_2)
        self.btnSearch.setObjectName("btnSearch")
        self.horizontalLayout_2.addWidget(self.btnSearch)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frameParamRight)
        self.tabBox.addTab(self.tabParameters, "")
        self.tabResults = QtWidgets.QWidget()
        self.tabResults.setObjectName("tabResults")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tabResults)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.tabResults)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(2)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblResults = QtWidgets.QLabel(self.frame_4)
        self.lblResults.setObjectName("lblResults")
        self.horizontalLayout_5.addWidget(self.lblResults)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.btnClearLog = QtWidgets.QPushButton(self.frame_4)
        self.btnClearLog.setObjectName("btnClearLog")
        self.horizontalLayout_5.addWidget(self.btnClearLog)
        self.btnSearch2 = QtWidgets.QPushButton(self.frame_4)
        self.btnSearch2.setObjectName("btnSearch2")
        self.horizontalLayout_5.addWidget(self.btnSearch2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.logResults = QtWidgets.QTextBrowser(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logResults.sizePolicy().hasHeightForWidth())
        self.logResults.setSizePolicy(sizePolicy)
        self.logResults.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logResults.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.logResults.setLineWidth(1)
        self.logResults.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.logResults.setReadOnly(True)
        self.logResults.setObjectName("logResults")
        self.verticalLayout_6.addWidget(self.logResults)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.tabResults)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setLineWidth(2)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.btnPlot = QtWidgets.QPushButton(self.frame_5)
        self.btnPlot.setObjectName("btnPlot")
        self.verticalLayout_5.addWidget(self.btnPlot)
        self.horizontalLayout_4.addWidget(self.frame_5)
        self.tabBox.addTab(self.tabResults, "")
        self.verticalLayout_3.addWidget(self.tabBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1049, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Powell Powell"))
        self.lblProgramTitle.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Powell-Powell - solving minimum of function with constraints</span></p></body></html>"))
        self.lblObjFunc.setText(_translate("MainWindow", "Objective function:"))
        self.cmbObjFun.setItemText(0, _translate("MainWindow", "(x1-2)^2+(x2-1)^2"))
        self.cmbObjFun.setItemText(1, _translate("MainWindow", "100(x2-x1^2)^2+(1-x1)^2"))
        self.cmbObjFun.setItemText(2, _translate("MainWindow", "100(x2-x1^2)^2+(100-x1)^2"))
        self.lblfx.setText(_translate("MainWindow", "f(x)="))
        self.lblVariables.setText(_translate("MainWindow", "Number of variables (n):"))
        self.cmbVariables.setItemText(0, _translate("MainWindow", "1"))
        self.cmbVariables.setItemText(1, _translate("MainWindow", "2"))
        self.cmbVariables.setItemText(2, _translate("MainWindow", "3"))
        self.cmbVariables.setItemText(3, _translate("MainWindow", "4"))
        self.cmbVariables.setItemText(4, _translate("MainWindow", "5"))
        self.lblConstraints.setText(_translate("MainWindow", "Number of constraints (m):"))
        self.cmbConstraints.setItemText(0, _translate("MainWindow", "0"))
        self.cmbConstraints.setItemText(1, _translate("MainWindow", "1"))
        self.cmbConstraints.setItemText(2, _translate("MainWindow", "2"))
        self.cmbConstraints.setItemText(3, _translate("MainWindow", "3"))
        self.cmbConstraints.setItemText(4, _translate("MainWindow", "4"))
        self.cmbConstraints.setItemText(5, _translate("MainWindow", "5"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Parameters for Powell method without constraints:</span></p></body></html>"))
        self.lblMaxIterations.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Number of interations (L):</span></p></body></html>"))
        self.cmbMaxIterations.setItemText(0, _translate("MainWindow", "100"))
        self.cmbMaxIterations.setItemText(1, _translate("MainWindow", "200"))
        self.cmbMaxIterations.setItemText(2, _translate("MainWindow", "400"))
        self.cmbMaxIterations.setItemText(3, _translate("MainWindow", "600"))
        self.cmbMaxIterations.setItemText(4, _translate("MainWindow", "800"))
        self.cmbMaxIterations.setItemText(5, _translate("MainWindow", "1000"))
        self.cmbPowellEpsilon.setItemText(0, _translate("MainWindow", "0.01"))
        self.cmbPowellEpsilon.setItemText(1, _translate("MainWindow", "1e-3"))
        self.cmbPowellEpsilon.setItemText(2, _translate("MainWindow", "1e-4"))
        self.cmbPowellEpsilon.setItemText(3, _translate("MainWindow", "1e-5"))
        self.cmbPowellEpsilon.setItemText(4, _translate("MainWindow", "1e-6"))
        self.cmbPowellEpsilon.setItemText(5, _translate("MainWindow", "1e-7"))
        self.cmbPowellEpsilon.setItemText(6, _translate("MainWindow", "1e-8"))
        self.lblEpsilon.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Epsilon:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Parameters for Powell method with constraints:</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "cMin"))
        self.label_8.setText(_translate("MainWindow", "m1"))
        self.label_9.setText(_translate("MainWindow", "m2"))
        self.gbStartPoint.setTitle(_translate("MainWindow", "Starting point:"))
        self.lbX0_2.setText(_translate("MainWindow", "x0_2:"))
        self.lbX0_1.setText(_translate("MainWindow", "x0_1:"))
        self.lbX0_4.setText(_translate("MainWindow", "x0_4"))
        self.lbX0_3.setText(_translate("MainWindow", "x0_3:"))
        self.lbX0_5.setText(_translate("MainWindow", "x0_5"))
        self.inputX0_1.setText(_translate("MainWindow", "0"))
        self.inputX0_2.setText(_translate("MainWindow", "0"))
        self.inputX0_3.setText(_translate("MainWindow", "0"))
        self.inputX0_4.setText(_translate("MainWindow", "0"))
        self.inputX0_5.setText(_translate("MainWindow", "0"))
        self.groupBoxConstraints.setTitle(_translate("MainWindow", "Constraints for searching for minimum:"))
        self.lblConstraint5.setText(_translate("MainWindow", "Constraint 5:"))
        self.lblConstraint4.setText(_translate("MainWindow", "Constraint 4:"))
        self.lblConstraint1.setText(_translate("MainWindow", "Constraint 1:"))
        self.lblConstraint2.setText(_translate("MainWindow", "Constraint 2:"))
        self.inputConstraint1.setText(_translate("MainWindow", "0"))
        self.lblConstraint3.setText(_translate("MainWindow", "Constraint 3:"))
        self.inputConstraint3.setText(_translate("MainWindow", "0"))
        self.inputConstraint2.setText(_translate("MainWindow", "0"))
        self.inputConstraint5.setText(_translate("MainWindow", "0"))
        self.inputConstraint4.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "<=0"))
        self.label_2.setText(_translate("MainWindow", "<=0"))
        self.label_3.setText(_translate("MainWindow", "<=0"))
        self.label_4.setText(_translate("MainWindow", "<=0"))
        self.label_10.setText(_translate("MainWindow", "<=0"))
        self.btnSearch.setText(_translate("MainWindow", "Search"))
        self.tabBox.setTabText(self.tabBox.indexOf(self.tabParameters), _translate("MainWindow", "Parameters"))
        self.lblResults.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Results:</span></p></body></html>"))
        self.btnClearLog.setText(_translate("MainWindow", "Clear log"))
        self.btnSearch2.setText(_translate("MainWindow", "Search"))
        self.btnPlot.setText(_translate("MainWindow", "Show plot"))
        self.tabBox.setTabText(self.tabBox.indexOf(self.tabResults), _translate("MainWindow", "Results"))

