# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'programQt.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1091, 839)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblProgramTitle = QtWidgets.QLabel(self.frame)
        self.lblProgramTitle.setObjectName("lblProgramTitle")
        self.verticalLayout_2.addWidget(self.lblProgramTitle)
        self.frameFunctionDetails = QtWidgets.QFrame(self.frame)
        self.frameFunctionDetails.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFunctionDetails.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFunctionDetails.setObjectName("frameFunctionDetails")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frameFunctionDetails)
        self.gridLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalFrame = QtWidgets.QFrame(self.frameFunctionDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalFrame.sizePolicy().hasHeightForWidth())
        self.verticalFrame.setSizePolicy(sizePolicy)
        self.verticalFrame.setObjectName("verticalFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.verticalFrame)
        self.gridLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblObjFunc = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblObjFunc.sizePolicy().hasHeightForWidth())
        self.lblObjFunc.setSizePolicy(sizePolicy)
        self.lblObjFunc.setObjectName("lblObjFunc")
        self.gridLayout_3.addWidget(self.lblObjFunc, 0, 1, 1, 1)
        self.cmbObjFun = QtWidgets.QComboBox(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbObjFun.sizePolicy().hasHeightForWidth())
        self.cmbObjFun.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cmbObjFun.setFont(font)
        self.cmbObjFun.setEditable(True)
        self.cmbObjFun.setObjectName("cmbObjFun")
        self.cmbObjFun.addItem("")
        self.cmbObjFun.addItem("")
        self.cmbObjFun.addItem("")
        self.cmbObjFun.addItem("")
        self.cmbObjFun.addItem("")
        self.gridLayout_3.addWidget(self.cmbObjFun, 1, 1, 1, 1)
        self.lblfx = QtWidgets.QLabel(self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblfx.sizePolicy().hasHeightForWidth())
        self.lblfx.setSizePolicy(sizePolicy)
        self.lblfx.setObjectName("lblfx")
        self.gridLayout_3.addWidget(self.lblfx, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.verticalFrame, 0, 2, 1, 1)
        self.frmFunDetails = QtWidgets.QFrame(self.frameFunctionDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frmFunDetails.sizePolicy().hasHeightForWidth())
        self.frmFunDetails.setSizePolicy(sizePolicy)
        self.frmFunDetails.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmFunDetails.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmFunDetails.setObjectName("frmFunDetails")
        self.gridLayout = QtWidgets.QGridLayout(self.frmFunDetails)
        self.gridLayout.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lblVariables = QtWidgets.QLabel(self.frmFunDetails)
        self.lblVariables.setObjectName("lblVariables")
        self.gridLayout.addWidget(self.lblVariables, 0, 0, 1, 1)
        self.cmbVariables = QtWidgets.QComboBox(self.frmFunDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbVariables.sizePolicy().hasHeightForWidth())
        self.cmbVariables.setSizePolicy(sizePolicy)
        self.cmbVariables.setObjectName("cmbVariables")
        self.cmbVariables.addItem("")
        self.cmbVariables.addItem("")
        self.cmbVariables.addItem("")
        self.cmbVariables.addItem("")
        self.cmbVariables.addItem("")
        self.gridLayout.addWidget(self.cmbVariables, 0, 1, 1, 1)
        self.lblConstraints = QtWidgets.QLabel(self.frmFunDetails)
        self.lblConstraints.setObjectName("lblConstraints")
        self.gridLayout.addWidget(self.lblConstraints, 1, 0, 1, 1)
        self.cmbConstraints = QtWidgets.QComboBox(self.frmFunDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbConstraints.sizePolicy().hasHeightForWidth())
        self.cmbConstraints.setSizePolicy(sizePolicy)
        self.cmbConstraints.setObjectName("cmbConstraints")
        self.cmbConstraints.addItem("")
        self.cmbConstraints.addItem("")
        self.cmbConstraints.addItem("")
        self.cmbConstraints.addItem("")
        self.cmbConstraints.addItem("")
        self.cmbConstraints.addItem("")
        self.gridLayout.addWidget(self.cmbConstraints, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frmFunDetails, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frameFunctionDetails)
        self.verticalLayout_3.addWidget(self.frame)
        self.tabBox = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabBox.sizePolicy().hasHeightForWidth())
        self.tabBox.setSizePolicy(sizePolicy)
        self.tabBox.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabBox.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabBox.setElideMode(QtCore.Qt.ElideLeft)
        self.tabBox.setObjectName("tabBox")
        self.tabParameters = QtWidgets.QWidget()
        self.tabParameters.setObjectName("tabParameters")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabParameters)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.parameters = QtWidgets.QGridLayout()
        self.parameters.setSpacing(1)
        self.parameters.setObjectName("parameters")
        self.gbParamPowell = QtWidgets.QGroupBox(self.tabParameters)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gbParamPowell.setFont(font)
        self.gbParamPowell.setObjectName("gbParamPowell")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gbParamPowell)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.gbParamPowell)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.frame_3 = QtWidgets.QFrame(self.gbParamPowell)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lblMaxIterations = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMaxIterations.sizePolicy().hasHeightForWidth())
        self.lblMaxIterations.setSizePolicy(sizePolicy)
        self.lblMaxIterations.setObjectName("lblMaxIterations")
        self.gridLayout_6.addWidget(self.lblMaxIterations, 0, 0, 1, 1)
        self.cmbMaxIterations = QtWidgets.QComboBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.cmbMaxIterations.sizePolicy().hasHeightForWidth())
        self.cmbMaxIterations.setSizePolicy(sizePolicy)
        self.cmbMaxIterations.setMinimumSize(QtCore.QSize(0, 15))
        self.cmbMaxIterations.setEditable(True)
        self.cmbMaxIterations.setObjectName("cmbMaxIterations")
        self.cmbMaxIterations.addItem("")
        self.cmbMaxIterations.addItem("")
        self.cmbMaxIterations.addItem("")
        self.cmbMaxIterations.addItem("")
        self.cmbMaxIterations.addItem("")
        self.cmbMaxIterations.addItem("")
        self.gridLayout_6.addWidget(self.cmbMaxIterations, 0, 1, 1, 1)
        self.lblEpsilon = QtWidgets.QLabel(self.frame_3)
        self.lblEpsilon.setObjectName("lblEpsilon")
        self.gridLayout_6.addWidget(self.lblEpsilon, 1, 0, 1, 1)
        self.cmbPowellEpsilon = QtWidgets.QComboBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.cmbPowellEpsilon.sizePolicy().hasHeightForWidth())
        self.cmbPowellEpsilon.setSizePolicy(sizePolicy)
        self.cmbPowellEpsilon.setMinimumSize(QtCore.QSize(0, 15))
        self.cmbPowellEpsilon.setEditable(True)
        self.cmbPowellEpsilon.setObjectName("cmbPowellEpsilon")
        self.cmbPowellEpsilon.addItem("")
        self.cmbPowellEpsilon.addItem("")
        self.cmbPowellEpsilon.addItem("")
        self.cmbPowellEpsilon.addItem("")
        self.cmbPowellEpsilon.addItem("")
        self.cmbPowellEpsilon.addItem("")
        self.gridLayout_6.addWidget(self.cmbPowellEpsilon, 1, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.label_6 = QtWidgets.QLabel(self.gbParamPowell)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.frmPowellConstrParams = QtWidgets.QFrame(self.gbParamPowell)
        self.frmPowellConstrParams.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmPowellConstrParams.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmPowellConstrParams.setObjectName("frmPowellConstrParams")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frmPowellConstrParams)
        self.gridLayout_7.setContentsMargins(-1, 0, -1, 11)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lblPowellConstrParamM1_2 = QtWidgets.QLabel(self.frmPowellConstrParams)
        self.lblPowellConstrParamM1_2.setObjectName("lblPowellConstrParamM1_2")
        self.gridLayout_7.addWidget(self.lblPowellConstrParamM1_2, 3, 0, 1, 1)
        self.lblPowellConstrParamM1 = QtWidgets.QLabel(self.frmPowellConstrParams)
        self.lblPowellConstrParamM1.setObjectName("lblPowellConstrParamM1")
        self.gridLayout_7.addWidget(self.lblPowellConstrParamM1, 1, 0, 2, 1)
        self.hSldM1 = QtWidgets.QSlider(self.frmPowellConstrParams)
        self.hSldM1.setMaximum(1000)
        self.hSldM1.setSingleStep(1)
        self.hSldM1.setProperty("value", 250)
        self.hSldM1.setOrientation(QtCore.Qt.Horizontal)
        self.hSldM1.setObjectName("hSldM1")
        self.gridLayout_7.addWidget(self.hSldM1, 1, 1, 1, 1)
        self.lblPowellConstrParamCMin = QtWidgets.QLabel(self.frmPowellConstrParams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPowellConstrParamCMin.sizePolicy().hasHeightForWidth())
        self.lblPowellConstrParamCMin.setSizePolicy(sizePolicy)
        self.lblPowellConstrParamCMin.setObjectName("lblPowellConstrParamCMin")
        self.gridLayout_7.addWidget(self.lblPowellConstrParamCMin, 0, 0, 1, 1)
        self.dSBM1 = QtWidgets.QDoubleSpinBox(self.frmPowellConstrParams)
        self.dSBM1.setMinimumSize(QtCore.QSize(0, 20))
        self.dSBM1.setDecimals(6)
        self.dSBM1.setMaximum(1.0)
        self.dSBM1.setSingleStep(1e-06)
        self.dSBM1.setProperty("value", 0.25)
        self.dSBM1.setObjectName("dSBM1")
        self.gridLayout_7.addWidget(self.dSBM1, 1, 2, 1, 1)
        self.hSldM2 = QtWidgets.QSlider(self.frmPowellConstrParams)
        self.hSldM2.setMinimum(10)
        self.hSldM2.setMaximum(1000)
        self.hSldM2.setSingleStep(1)
        self.hSldM2.setProperty("value", 100)
        self.hSldM2.setOrientation(QtCore.Qt.Horizontal)
        self.hSldM2.setObjectName("hSldM2")
        self.gridLayout_7.addWidget(self.hSldM2, 3, 1, 1, 1)
        self.dSBM2 = QtWidgets.QDoubleSpinBox(self.frmPowellConstrParams)
        self.dSBM2.setMinimumSize(QtCore.QSize(0, 20))
        self.dSBM2.setDecimals(5)
        self.dSBM2.setMinimum(1.0)
        self.dSBM2.setMaximum(100.0)
        self.dSBM2.setSingleStep(1e-05)
        self.dSBM2.setProperty("value", 10.0)
        self.dSBM2.setObjectName("dSBM2")
        self.gridLayout_7.addWidget(self.dSBM2, 3, 2, 1, 1)
        self.hSldcMin = QtWidgets.QSlider(self.frmPowellConstrParams)
        self.hSldcMin.setMinimum(1)
        self.hSldcMin.setMaximum(5705000)
        self.hSldcMin.setSingleStep(1)
        self.hSldcMin.setProperty("value", 1000000)
        self.hSldcMin.setOrientation(QtCore.Qt.Horizontal)
        self.hSldcMin.setObjectName("hSldcMin")
        self.gridLayout_7.addWidget(self.hSldcMin, 0, 1, 1, 1)
        self.inputcMin = QtWidgets.QLineEdit(self.frmPowellConstrParams)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputcMin.sizePolicy().hasHeightForWidth())
        self.inputcMin.setSizePolicy(sizePolicy)
        self.inputcMin.setMaximumSize(QtCore.QSize(150, 16777215))
        self.inputcMin.setObjectName("inputcMin")
        self.gridLayout_7.addWidget(self.inputcMin, 0, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.frmPowellConstrParams)
        self.parameters.addWidget(self.gbParamPowell, 1, 0, 1, 1)
        self.gbConstraints = QtWidgets.QGroupBox(self.tabParameters)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gbConstraints.setFont(font)
        self.gbConstraints.setObjectName("gbConstraints")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gbConstraints)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setVerticalSpacing(1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblConstraint5 = QtWidgets.QLabel(self.gbConstraints)
        self.lblConstraint5.setObjectName("lblConstraint5")
        self.gridLayout_4.addWidget(self.lblConstraint5, 4, 0, 1, 1)
        self.lblConstraint3 = QtWidgets.QLabel(self.gbConstraints)
        self.lblConstraint3.setObjectName("lblConstraint3")
        self.gridLayout_4.addWidget(self.lblConstraint3, 2, 0, 1, 1)
        self.lblConstraint2 = QtWidgets.QLabel(self.gbConstraints)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblConstraint2.sizePolicy().hasHeightForWidth())
        self.lblConstraint2.setSizePolicy(sizePolicy)
        self.lblConstraint2.setObjectName("lblConstraint2")
        self.gridLayout_4.addWidget(self.lblConstraint2, 1, 0, 1, 1)
        self.inputConstraint1 = QtWidgets.QLineEdit(self.gbConstraints)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputConstraint1.setFont(font)
        self.inputConstraint1.setObjectName("inputConstraint1")
        self.gridLayout_4.addWidget(self.inputConstraint1, 0, 1, 1, 1)
        self.lblConstraint1 = QtWidgets.QLabel(self.gbConstraints)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblConstraint1.sizePolicy().hasHeightForWidth())
        self.lblConstraint1.setSizePolicy(sizePolicy)
        self.lblConstraint1.setObjectName("lblConstraint1")
        self.gridLayout_4.addWidget(self.lblConstraint1, 0, 0, 1, 1)
        self.lblConstraint4 = QtWidgets.QLabel(self.gbConstraints)
        self.lblConstraint4.setObjectName("lblConstraint4")
        self.gridLayout_4.addWidget(self.lblConstraint4, 3, 0, 1, 1)
        self.inputConstraint5 = QtWidgets.QLineEdit(self.gbConstraints)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputConstraint5.setFont(font)
        self.inputConstraint5.setObjectName("inputConstraint5")
        self.gridLayout_4.addWidget(self.inputConstraint5, 4, 1, 1, 1)
        self.inputConstraint4 = QtWidgets.QLineEdit(self.gbConstraints)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputConstraint4.setFont(font)
        self.inputConstraint4.setObjectName("inputConstraint4")
        self.gridLayout_4.addWidget(self.inputConstraint4, 3, 1, 1, 1)
        self.inputConstraint2 = QtWidgets.QLineEdit(self.gbConstraints)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputConstraint2.setFont(font)
        self.inputConstraint2.setObjectName("inputConstraint2")
        self.gridLayout_4.addWidget(self.inputConstraint2, 1, 1, 1, 1)
        self.lblConstrEq1 = QtWidgets.QLabel(self.gbConstraints)
        self.lblConstrEq1.setObjectName("lblConstrEq1")
        self.gridLayout_4.addWidget(self.lblConstrEq1, 0, 2, 1, 1)
        self.inputConstraint3 = QtWidgets.QLineEdit(self.gbConstraints)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputConstraint3.setFont(font)
        self.inputConstraint3.setObjectName("inputConstraint3")
        self.gridLayout_4.addWidget(self.inputConstraint3, 2, 1, 1, 1)
        self.lblConstrEq2 = QtWidgets.QLabel(self.gbConstraints)
        self.lblConstrEq2.setObjectName("lblConstrEq2")
        self.gridLayout_4.addWidget(self.lblConstrEq2, 1, 2, 1, 1)
        self.lblConstrEq3 = QtWidgets.QLabel(self.gbConstraints)
        self.lblConstrEq3.setObjectName("lblConstrEq3")
        self.gridLayout_4.addWidget(self.lblConstrEq3, 2, 2, 1, 1)
        self.lblConstrEq4 = QtWidgets.QLabel(self.gbConstraints)
        self.lblConstrEq4.setObjectName("lblConstrEq4")
        self.gridLayout_4.addWidget(self.lblConstrEq4, 3, 2, 1, 1)
        self.lblConstrEq5 = QtWidgets.QLabel(self.gbConstraints)
        self.lblConstrEq5.setObjectName("lblConstrEq5")
        self.gridLayout_4.addWidget(self.lblConstrEq5, 4, 2, 1, 1)
        self.parameters.addWidget(self.gbConstraints, 0, 0, 1, 1)
        self.gbConstrParameters = QtWidgets.QGroupBox(self.tabParameters)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gbConstrParameters.setFont(font)
        self.gbConstrParameters.setObjectName("gbConstrParameters")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gbConstrParameters)
        self.gridLayout_8.setVerticalSpacing(1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem2, 0, 4, 1, 1)
        self.lblConstraint1_2 = QtWidgets.QLabel(self.gbConstrParameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblConstraint1_2.sizePolicy().hasHeightForWidth())
        self.lblConstraint1_2.setSizePolicy(sizePolicy)
        self.lblConstraint1_2.setObjectName("lblConstraint1_2")
        self.gridLayout_8.addWidget(self.lblConstraint1_2, 0, 0, 1, 1)
        self.lblConstrDelta1 = QtWidgets.QLabel(self.gbConstrParameters)
        self.lblConstrDelta1.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lblConstrDelta1.setObjectName("lblConstrDelta1")
        self.gridLayout_8.addWidget(self.lblConstrDelta1, 0, 2, 1, 1)
        self.lblConstrTheta1 = QtWidgets.QLabel(self.gbConstrParameters)
        self.lblConstrTheta1.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lblConstrTheta1.setObjectName("lblConstrTheta1")
        self.gridLayout_8.addWidget(self.lblConstrTheta1, 0, 5, 1, 1)
        self.dsbConstrDelta1 = QtWidgets.QDoubleSpinBox(self.gbConstrParameters)
        self.dsbConstrDelta1.setDecimals(3)
        self.dsbConstrDelta1.setMinimum(0.001)
        self.dsbConstrDelta1.setMaximum(999999.0)
        self.dsbConstrDelta1.setSingleStep(0.001)
        self.dsbConstrDelta1.setProperty("value", 1.0)
        self.dsbConstrDelta1.setObjectName("dsbConstrDelta1")
        self.gridLayout_8.addWidget(self.dsbConstrDelta1, 0, 3, 1, 1)
        self.dsbConstrTheta1 = QtWidgets.QDoubleSpinBox(self.gbConstrParameters)
        self.dsbConstrTheta1.setDecimals(3)
        self.dsbConstrTheta1.setMinimum(0.0)
        self.dsbConstrTheta1.setMaximum(999.999)
        self.dsbConstrTheta1.setSingleStep(0.001)
        self.dsbConstrTheta1.setProperty("value", 0.0)
        self.dsbConstrTheta1.setObjectName("dsbConstrTheta1")
        self.gridLayout_8.addWidget(self.dsbConstrTheta1, 0, 6, 1, 1)
        self.lblConstraint2_2 = QtWidgets.QLabel(self.gbConstrParameters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblConstraint2_2.sizePolicy().hasHeightForWidth())
        self.lblConstraint2_2.setSizePolicy(sizePolicy)
        self.lblConstraint2_2.setObjectName("lblConstraint2_2")
        self.gridLayout_8.addWidget(self.lblConstraint2_2, 1, 0, 1, 1)
        self.lblConstraint3_2 = QtWidgets.QLabel(self.gbConstrParameters)
        self.lblConstraint3_2.setObjectName("lblConstraint3_2")
        self.gridLayout_8.addWidget(self.lblConstraint3_2, 2, 0, 1, 1)
        self.lblConstraint4_2 = QtWidgets.QLabel(self.gbConstrParameters)
        self.lblConstraint4_2.setObjectName("lblConstraint4_2")
        self.gridLayout_8.addWidget(self.lblConstraint4_2, 3, 0, 1, 1)
        self.lblConstraint5_2 = QtWidgets.QLabel(self.gbConstrParameters)
        self.lblConstraint5_2.setObjectName("lblConstraint5_2")
        self.gridLayout_8.addWidget(self.lblConstraint5_2, 4, 0, 1, 1)
        self.lblConstrDelta2 = QtWidgets.QLabel(self.gbConstrParameters)
        self.lblConstrDelta2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lblConstrDelta2.setObjectName("lblConstrDelta2")
        self.gridLayout_8.addWidget(self.lblConstrDelta2, 1, 2, 1, 1)
        self.lblConstrTheta2 = QtWidgets.QLabel(self.gbConstrParameters)
        self.lblConstrTheta2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lblConstrTheta2.setObjectName("lblConstrTheta2")
        self.gridLayout_8.addWidget(self.lblConstrTheta2, 1, 5, 1, 1)
        self.lblConstrDelta3 = QtWidgets.QLabel(self.gbConstrParameters)
        self.lblConstrDelta3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lblConstrDelta3.setObjectName("lblConstrDelta3")
        self.gridLayout_8.addWidget(self.lblConstrDelta3, 2, 2, 1, 1)
        self.lblConstrTheta3 = QtWidgets.QLabel(self.gbConstrParameters)
        self.lblConstrTheta3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lblConstrTheta3.setObjectName("lblConstrTheta3")
        self.gridLayout_8.addWidget(self.lblConstrTheta3, 2, 5, 1, 1)
        self.lblConstrTheta5 = QtWidgets.QLabel(self.gbConstrParameters)
        self.lblConstrTheta5.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lblConstrTheta5.setObjectName("lblConstrTheta5")
        self.gridLayout_8.addWidget(self.lblConstrTheta5, 4, 5, 1, 1)
        self.lblConstrTheta4 = QtWidgets.QLabel(self.gbConstrParameters)
        self.lblConstrTheta4.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lblConstrTheta4.setObjectName("lblConstrTheta4")
        self.gridLayout_8.addWidget(self.lblConstrTheta4, 3, 5, 1, 1)
        self.lblConstrDelta4 = QtWidgets.QLabel(self.gbConstrParameters)
        self.lblConstrDelta4.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lblConstrDelta4.setObjectName("lblConstrDelta4")
        self.gridLayout_8.addWidget(self.lblConstrDelta4, 3, 2, 1, 1)
        self.lblConstrDelta5 = QtWidgets.QLabel(self.gbConstrParameters)
        self.lblConstrDelta5.setMaximumSize(QtCore.QSize(30, 16777215))
        self.lblConstrDelta5.setObjectName("lblConstrDelta5")
        self.gridLayout_8.addWidget(self.lblConstrDelta5, 4, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem3, 0, 1, 1, 1)
        self.dsbConstrDelta2 = QtWidgets.QDoubleSpinBox(self.gbConstrParameters)
        self.dsbConstrDelta2.setDecimals(3)
        self.dsbConstrDelta2.setMinimum(0.001)
        self.dsbConstrDelta2.setMaximum(999999.0)
        self.dsbConstrDelta2.setSingleStep(0.001)
        self.dsbConstrDelta2.setProperty("value", 1.0)
        self.dsbConstrDelta2.setObjectName("dsbConstrDelta2")
        self.gridLayout_8.addWidget(self.dsbConstrDelta2, 1, 3, 1, 1)
        self.dsbConstrDelta3 = QtWidgets.QDoubleSpinBox(self.gbConstrParameters)
        self.dsbConstrDelta3.setDecimals(3)
        self.dsbConstrDelta3.setMinimum(0.001)
        self.dsbConstrDelta3.setMaximum(999999.0)
        self.dsbConstrDelta3.setSingleStep(0.001)
        self.dsbConstrDelta3.setProperty("value", 1.0)
        self.dsbConstrDelta3.setObjectName("dsbConstrDelta3")
        self.gridLayout_8.addWidget(self.dsbConstrDelta3, 2, 3, 1, 1)
        self.dsbConstrDelta4 = QtWidgets.QDoubleSpinBox(self.gbConstrParameters)
        self.dsbConstrDelta4.setDecimals(3)
        self.dsbConstrDelta4.setMinimum(0.001)
        self.dsbConstrDelta4.setMaximum(999999.0)
        self.dsbConstrDelta4.setSingleStep(0.001)
        self.dsbConstrDelta4.setProperty("value", 1.0)
        self.dsbConstrDelta4.setObjectName("dsbConstrDelta4")
        self.gridLayout_8.addWidget(self.dsbConstrDelta4, 3, 3, 1, 1)
        self.dsbConstrDelta5 = QtWidgets.QDoubleSpinBox(self.gbConstrParameters)
        self.dsbConstrDelta5.setDecimals(3)
        self.dsbConstrDelta5.setMinimum(0.001)
        self.dsbConstrDelta5.setMaximum(999999.0)
        self.dsbConstrDelta5.setSingleStep(0.001)
        self.dsbConstrDelta5.setProperty("value", 1.0)
        self.dsbConstrDelta5.setObjectName("dsbConstrDelta5")
        self.gridLayout_8.addWidget(self.dsbConstrDelta5, 4, 3, 1, 1)
        self.dsbConstrTheta2 = QtWidgets.QDoubleSpinBox(self.gbConstrParameters)
        self.dsbConstrTheta2.setDecimals(3)
        self.dsbConstrTheta2.setMinimum(0.0)
        self.dsbConstrTheta2.setMaximum(999.999)
        self.dsbConstrTheta2.setSingleStep(0.001)
        self.dsbConstrTheta2.setProperty("value", 0.0)
        self.dsbConstrTheta2.setObjectName("dsbConstrTheta2")
        self.gridLayout_8.addWidget(self.dsbConstrTheta2, 1, 6, 1, 1)
        self.dsbConstrTheta3 = QtWidgets.QDoubleSpinBox(self.gbConstrParameters)
        self.dsbConstrTheta3.setDecimals(3)
        self.dsbConstrTheta3.setMinimum(0.0)
        self.dsbConstrTheta3.setMaximum(999.999)
        self.dsbConstrTheta3.setSingleStep(0.001)
        self.dsbConstrTheta3.setProperty("value", 0.0)
        self.dsbConstrTheta3.setObjectName("dsbConstrTheta3")
        self.gridLayout_8.addWidget(self.dsbConstrTheta3, 2, 6, 1, 1)
        self.dsbConstrTheta4 = QtWidgets.QDoubleSpinBox(self.gbConstrParameters)
        self.dsbConstrTheta4.setDecimals(3)
        self.dsbConstrTheta4.setMinimum(0.0)
        self.dsbConstrTheta4.setMaximum(999.999)
        self.dsbConstrTheta4.setSingleStep(0.001)
        self.dsbConstrTheta4.setProperty("value", 0.0)
        self.dsbConstrTheta4.setObjectName("dsbConstrTheta4")
        self.gridLayout_8.addWidget(self.dsbConstrTheta4, 3, 6, 1, 1)
        self.dsbConstrTheta5 = QtWidgets.QDoubleSpinBox(self.gbConstrParameters)
        self.dsbConstrTheta5.setDecimals(3)
        self.dsbConstrTheta5.setMinimum(0.0)
        self.dsbConstrTheta5.setMaximum(999.999)
        self.dsbConstrTheta5.setSingleStep(0.001)
        self.dsbConstrTheta5.setProperty("value", 0.0)
        self.dsbConstrTheta5.setObjectName("dsbConstrTheta5")
        self.gridLayout_8.addWidget(self.dsbConstrTheta5, 4, 6, 1, 1)
        self.parameters.addWidget(self.gbConstrParameters, 0, 1, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gbStartPoint = QtWidgets.QGroupBox(self.tabParameters)
        self.gbStartPoint.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbStartPoint.sizePolicy().hasHeightForWidth())
        self.gbStartPoint.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gbStartPoint.setFont(font)
        self.gbStartPoint.setFlat(False)
        self.gbStartPoint.setCheckable(False)
        self.gbStartPoint.setObjectName("gbStartPoint")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gbStartPoint)
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_5.setVerticalSpacing(1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lbX0_1 = QtWidgets.QLabel(self.gbStartPoint)
        self.lbX0_1.setObjectName("lbX0_1")
        self.gridLayout_5.addWidget(self.lbX0_1, 0, 0, 1, 1)
        self.lbX0_4 = QtWidgets.QLabel(self.gbStartPoint)
        self.lbX0_4.setObjectName("lbX0_4")
        self.gridLayout_5.addWidget(self.lbX0_4, 4, 0, 1, 1)
        self.lbX0_5 = QtWidgets.QLabel(self.gbStartPoint)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbX0_5.sizePolicy().hasHeightForWidth())
        self.lbX0_5.setSizePolicy(sizePolicy)
        self.lbX0_5.setObjectName("lbX0_5")
        self.gridLayout_5.addWidget(self.lbX0_5, 5, 0, 1, 1)
        self.lbX0_3 = QtWidgets.QLabel(self.gbStartPoint)
        self.lbX0_3.setObjectName("lbX0_3")
        self.gridLayout_5.addWidget(self.lbX0_3, 3, 0, 1, 1)
        self.inputX0_4 = QtWidgets.QLineEdit(self.gbStartPoint)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputX0_4.setFont(font)
        self.inputX0_4.setObjectName("inputX0_4")
        self.gridLayout_5.addWidget(self.inputX0_4, 4, 1, 1, 1)
        self.inputX0_5 = QtWidgets.QLineEdit(self.gbStartPoint)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputX0_5.setFont(font)
        self.inputX0_5.setObjectName("inputX0_5")
        self.gridLayout_5.addWidget(self.inputX0_5, 5, 1, 1, 1)
        self.lbX0_2 = QtWidgets.QLabel(self.gbStartPoint)
        self.lbX0_2.setObjectName("lbX0_2")
        self.gridLayout_5.addWidget(self.lbX0_2, 2, 0, 1, 1)
        self.inputX0_2 = QtWidgets.QLineEdit(self.gbStartPoint)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputX0_2.setFont(font)
        self.inputX0_2.setObjectName("inputX0_2")
        self.gridLayout_5.addWidget(self.inputX0_2, 2, 1, 1, 1)
        self.inputX0_3 = QtWidgets.QLineEdit(self.gbStartPoint)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputX0_3.setFont(font)
        self.inputX0_3.setObjectName("inputX0_3")
        self.gridLayout_5.addWidget(self.inputX0_3, 3, 1, 1, 1)
        self.inputX0_1 = QtWidgets.QLineEdit(self.gbStartPoint)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputX0_1.setFont(font)
        self.inputX0_1.setObjectName("inputX0_1")
        self.gridLayout_5.addWidget(self.inputX0_1, 0, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.gbStartPoint)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.gbSearchInDirection = QtWidgets.QGroupBox(self.tabParameters)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gbSearchInDirection.setFont(font)
        self.gbSearchInDirection.setObjectName("gbSearchInDirection")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.gbSearchInDirection)
        self.verticalLayout_9.setContentsMargins(-1, 0, -1, 11)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.checkBoxBracketing = QtWidgets.QCheckBox(self.gbSearchInDirection)
        self.checkBoxBracketing.setChecked(True)
        self.checkBoxBracketing.setObjectName("checkBoxBracketing")
        self.verticalLayout_9.addWidget(self.checkBoxBracketing)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setVerticalSpacing(1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lblGoldenSearchWindow = QtWidgets.QLabel(self.gbSearchInDirection)
        self.lblGoldenSearchWindow.setObjectName("lblGoldenSearchWindow")
        self.gridLayout_9.addWidget(self.lblGoldenSearchWindow, 1, 0, 1, 1)
        self.dsbGoldenSearchWindow = QtWidgets.QDoubleSpinBox(self.gbSearchInDirection)
        self.dsbGoldenSearchWindow.setDecimals(4)
        self.dsbGoldenSearchWindow.setMinimum(0.0001)
        self.dsbGoldenSearchWindow.setMaximum(10000000.0)
        self.dsbGoldenSearchWindow.setSingleStep(0.0001)
        self.dsbGoldenSearchWindow.setProperty("value", 1.0)
        self.dsbGoldenSearchWindow.setObjectName("dsbGoldenSearchWindow")
        self.gridLayout_9.addWidget(self.dsbGoldenSearchWindow, 1, 1, 1, 1)
        self.dsbBracketStep = QtWidgets.QDoubleSpinBox(self.gbSearchInDirection)
        self.dsbBracketStep.setDecimals(4)
        self.dsbBracketStep.setMinimum(0.0001)
        self.dsbBracketStep.setMaximum(100.0)
        self.dsbBracketStep.setSingleStep(0.0001)
        self.dsbBracketStep.setObjectName("dsbBracketStep")
        self.gridLayout_9.addWidget(self.dsbBracketStep, 0, 1, 1, 1)
        self.lblBracketStep = QtWidgets.QLabel(self.gbSearchInDirection)
        self.lblBracketStep.setObjectName("lblBracketStep")
        self.gridLayout_9.addWidget(self.lblBracketStep, 0, 0, 1, 1)
        self.lblGoldenSearchEpsilon = QtWidgets.QLabel(self.gbSearchInDirection)
        self.lblGoldenSearchEpsilon.setObjectName("lblGoldenSearchEpsilon")
        self.gridLayout_9.addWidget(self.lblGoldenSearchEpsilon, 2, 0, 1, 1)
        self.cmbGoldenSearchEpsilon = QtWidgets.QComboBox(self.gbSearchInDirection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.cmbGoldenSearchEpsilon.sizePolicy().hasHeightForWidth())
        self.cmbGoldenSearchEpsilon.setSizePolicy(sizePolicy)
        self.cmbGoldenSearchEpsilon.setMinimumSize(QtCore.QSize(0, 15))
        self.cmbGoldenSearchEpsilon.setEditable(True)
        self.cmbGoldenSearchEpsilon.setObjectName("cmbGoldenSearchEpsilon")
        self.cmbGoldenSearchEpsilon.addItem("")
        self.cmbGoldenSearchEpsilon.addItem("")
        self.cmbGoldenSearchEpsilon.addItem("")
        self.cmbGoldenSearchEpsilon.addItem("")
        self.cmbGoldenSearchEpsilon.addItem("")
        self.cmbGoldenSearchEpsilon.addItem("")
        self.cmbGoldenSearchEpsilon.addItem("")
        self.cmbGoldenSearchEpsilon.addItem("")
        self.cmbGoldenSearchEpsilon.addItem("")
        self.cmbGoldenSearchEpsilon.addItem("")
        self.cmbGoldenSearchEpsilon.addItem("")
        self.cmbGoldenSearchEpsilon.addItem("")
        self.cmbGoldenSearchEpsilon.addItem("")
        self.gridLayout_9.addWidget(self.cmbGoldenSearchEpsilon, 2, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_9)
        self.verticalLayout_7.addWidget(self.gbSearchInDirection)
        self.parameters.addLayout(self.verticalLayout_7, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.parameters)
        self.frmButtons = QtWidgets.QFrame(self.tabParameters)
        self.frmButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmButtons.setObjectName("frmButtons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frmButtons)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.btnSearch = QtWidgets.QPushButton(self.frmButtons)
        self.btnSearch.setObjectName("btnSearch")
        self.horizontalLayout.addWidget(self.btnSearch)
        self.verticalLayout.addWidget(self.frmButtons)
        self.tabBox.addTab(self.tabParameters, "")
        self.tabResults = QtWidgets.QWidget()
        self.tabResults.setObjectName("tabResults")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tabResults)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.tabResults)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(2)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblResults = QtWidgets.QLabel(self.frame_4)
        self.lblResults.setObjectName("lblResults")
        self.horizontalLayout_5.addWidget(self.lblResults)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.btnClearLog = QtWidgets.QPushButton(self.frame_4)
        self.btnClearLog.setObjectName("btnClearLog")
        self.horizontalLayout_5.addWidget(self.btnClearLog)
        self.btnSearch2 = QtWidgets.QPushButton(self.frame_4)
        self.btnSearch2.setObjectName("btnSearch2")
        self.horizontalLayout_5.addWidget(self.btnSearch2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.logResults = QtWidgets.QTextBrowser(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logResults.sizePolicy().hasHeightForWidth())
        self.logResults.setSizePolicy(sizePolicy)
        self.logResults.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logResults.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.logResults.setLineWidth(1)
        self.logResults.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.logResults.setReadOnly(True)
        self.logResults.setObjectName("logResults")
        self.verticalLayout_6.addWidget(self.logResults)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.tabResults)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setLineWidth(2)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.btnPlot = QtWidgets.QPushButton(self.frame_5)
        self.btnPlot.setObjectName("btnPlot")
        self.verticalLayout_5.addWidget(self.btnPlot)
        self.horizontalLayout_4.addWidget(self.frame_5)
        self.tabBox.addTab(self.tabResults, "")
        self.verticalLayout_3.addWidget(self.tabBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1091, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Powell Powell"))
        self.lblProgramTitle.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Powell-Powell - solving minimum of function with constraints</span></p></body></html>"))
        self.lblObjFunc.setText(_translate("MainWindow", "Objective function:"))
        self.cmbObjFun.setItemText(0, _translate("MainWindow", "(x1-2)^2+(x2-1)^2"))
        self.cmbObjFun.setItemText(1, _translate("MainWindow", "100(x2-x1^2)^2+(1-x1)^2"))
        self.cmbObjFun.setItemText(2, _translate("MainWindow", "x1^4+x2^4-2x1^2x2-4x1+3"))
        self.cmbObjFun.setItemText(3, _translate("MainWindow", "(x1^2+x2-11)^2+(x1+x2^2-7)^2"))
        self.cmbObjFun.setItemText(4, _translate("MainWindow", "x1^4+x2^4-x1^2-x2^2"))
        self.lblfx.setText(_translate("MainWindow", "f(x)="))
        self.lblVariables.setText(_translate("MainWindow", "Number of variables (n):"))
        self.cmbVariables.setItemText(0, _translate("MainWindow", "1"))
        self.cmbVariables.setItemText(1, _translate("MainWindow", "2"))
        self.cmbVariables.setItemText(2, _translate("MainWindow", "3"))
        self.cmbVariables.setItemText(3, _translate("MainWindow", "4"))
        self.cmbVariables.setItemText(4, _translate("MainWindow", "5"))
        self.lblConstraints.setText(_translate("MainWindow", "Number of constraints (m):"))
        self.cmbConstraints.setItemText(0, _translate("MainWindow", "0"))
        self.cmbConstraints.setItemText(1, _translate("MainWindow", "1"))
        self.cmbConstraints.setItemText(2, _translate("MainWindow", "2"))
        self.cmbConstraints.setItemText(3, _translate("MainWindow", "3"))
        self.cmbConstraints.setItemText(4, _translate("MainWindow", "4"))
        self.cmbConstraints.setItemText(5, _translate("MainWindow", "5"))
        self.gbParamPowell.setTitle(_translate("MainWindow", "Parameters for Powell methods:"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Parameters for Powell method without constraints:</span></p></body></html>"))
        self.lblMaxIterations.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Number of interations (L):</span></p></body></html>"))
        self.cmbMaxIterations.setItemText(0, _translate("MainWindow", "100"))
        self.cmbMaxIterations.setItemText(1, _translate("MainWindow", "200"))
        self.cmbMaxIterations.setItemText(2, _translate("MainWindow", "400"))
        self.cmbMaxIterations.setItemText(3, _translate("MainWindow", "600"))
        self.cmbMaxIterations.setItemText(4, _translate("MainWindow", "800"))
        self.cmbMaxIterations.setItemText(5, _translate("MainWindow", "1000"))
        self.lblEpsilon.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Epsilon:</span></p></body></html>"))
        self.cmbPowellEpsilon.setItemText(0, _translate("MainWindow", "1e-3"))
        self.cmbPowellEpsilon.setItemText(1, _translate("MainWindow", "1e-4"))
        self.cmbPowellEpsilon.setItemText(2, _translate("MainWindow", "1e-5"))
        self.cmbPowellEpsilon.setItemText(3, _translate("MainWindow", "1e-6"))
        self.cmbPowellEpsilon.setItemText(4, _translate("MainWindow", "1e-7"))
        self.cmbPowellEpsilon.setItemText(5, _translate("MainWindow", "1e-8"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Parameters for Powell method with constraints:</span></p></body></html>"))
        self.lblPowellConstrParamM1_2.setText(_translate("MainWindow", "m2"))
        self.lblPowellConstrParamM1.setText(_translate("MainWindow", "m1"))
        self.lblPowellConstrParamCMin.setText(_translate("MainWindow", "cMin"))
        self.inputcMin.setText(_translate("MainWindow", "0,1"))
        self.gbConstraints.setTitle(_translate("MainWindow", "Constraints for searching for minimum:"))
        self.lblConstraint5.setText(_translate("MainWindow", "Constraint 5:"))
        self.lblConstraint3.setText(_translate("MainWindow", "Constraint 3:"))
        self.lblConstraint2.setText(_translate("MainWindow", "Constraint 2:"))
        self.inputConstraint1.setText(_translate("MainWindow", "0"))
        self.lblConstraint1.setText(_translate("MainWindow", "Constraint 1:"))
        self.lblConstraint4.setText(_translate("MainWindow", "Constraint 4:"))
        self.inputConstraint5.setText(_translate("MainWindow", "0"))
        self.inputConstraint4.setText(_translate("MainWindow", "0"))
        self.inputConstraint2.setText(_translate("MainWindow", "0"))
        self.lblConstrEq1.setText(_translate("MainWindow", "<=0"))
        self.inputConstraint3.setText(_translate("MainWindow", "0"))
        self.lblConstrEq2.setText(_translate("MainWindow", "<=0"))
        self.lblConstrEq3.setText(_translate("MainWindow", "<=0"))
        self.lblConstrEq4.setText(_translate("MainWindow", "<=0"))
        self.lblConstrEq5.setText(_translate("MainWindow", "<=0"))
        self.gbConstrParameters.setTitle(_translate("MainWindow", "Constraints parameters:"))
        self.lblConstraint1_2.setText(_translate("MainWindow", "Constraint 1:"))
        self.lblConstrDelta1.setText(_translate("MainWindow", "delta1"))
        self.lblConstrTheta1.setText(_translate("MainWindow", "theta1"))
        self.lblConstraint2_2.setText(_translate("MainWindow", "Constraint 2:"))
        self.lblConstraint3_2.setText(_translate("MainWindow", "Constraint 3:"))
        self.lblConstraint4_2.setText(_translate("MainWindow", "Constraint 4:"))
        self.lblConstraint5_2.setText(_translate("MainWindow", "Constraint 5:"))
        self.lblConstrDelta2.setText(_translate("MainWindow", "delta2"))
        self.lblConstrTheta2.setText(_translate("MainWindow", "theta2"))
        self.lblConstrDelta3.setText(_translate("MainWindow", "delta3"))
        self.lblConstrTheta3.setText(_translate("MainWindow", "theta3"))
        self.lblConstrTheta5.setText(_translate("MainWindow", "theta4"))
        self.lblConstrTheta4.setText(_translate("MainWindow", "theta4"))
        self.lblConstrDelta4.setText(_translate("MainWindow", "delta4"))
        self.lblConstrDelta5.setText(_translate("MainWindow", "delta5"))
        self.gbStartPoint.setTitle(_translate("MainWindow", "Starting point:"))
        self.lbX0_1.setText(_translate("MainWindow", "x0_1:"))
        self.lbX0_4.setText(_translate("MainWindow", "x0_4"))
        self.lbX0_5.setText(_translate("MainWindow", "x0_5"))
        self.lbX0_3.setText(_translate("MainWindow", "x0_3:"))
        self.inputX0_4.setText(_translate("MainWindow", "0"))
        self.inputX0_5.setText(_translate("MainWindow", "0"))
        self.lbX0_2.setText(_translate("MainWindow", "x0_2:"))
        self.inputX0_2.setText(_translate("MainWindow", "0"))
        self.inputX0_3.setText(_translate("MainWindow", "0"))
        self.inputX0_1.setText(_translate("MainWindow", "0"))
        self.gbSearchInDirection.setTitle(_translate("MainWindow", "Searching in direction (Golden search):"))
        self.checkBoxBracketing.setText(_translate("MainWindow", "Minimum Bracketing"))
        self.lblGoldenSearchWindow.setText(_translate("MainWindow", "Golden search window [-h, h]:"))
        self.lblBracketStep.setText(_translate("MainWindow", "Bracket step (h):"))
        self.lblGoldenSearchEpsilon.setText(_translate("MainWindow", "Golden search epsilon:"))
        self.cmbGoldenSearchEpsilon.setItemText(0, _translate("MainWindow", "1e-3"))
        self.cmbGoldenSearchEpsilon.setItemText(1, _translate("MainWindow", "1e-4"))
        self.cmbGoldenSearchEpsilon.setItemText(2, _translate("MainWindow", "1e-5"))
        self.cmbGoldenSearchEpsilon.setItemText(3, _translate("MainWindow", "1e-6"))
        self.cmbGoldenSearchEpsilon.setItemText(4, _translate("MainWindow", "1e-7"))
        self.cmbGoldenSearchEpsilon.setItemText(5, _translate("MainWindow", "1e-8"))
        self.cmbGoldenSearchEpsilon.setItemText(6, _translate("MainWindow", "1e-9"))
        self.cmbGoldenSearchEpsilon.setItemText(7, _translate("MainWindow", "1e-10"))
        self.cmbGoldenSearchEpsilon.setItemText(8, _translate("MainWindow", "1e-11"))
        self.cmbGoldenSearchEpsilon.setItemText(9, _translate("MainWindow", "1e-12"))
        self.cmbGoldenSearchEpsilon.setItemText(10, _translate("MainWindow", "1e-13"))
        self.cmbGoldenSearchEpsilon.setItemText(11, _translate("MainWindow", "1e-14"))
        self.cmbGoldenSearchEpsilon.setItemText(12, _translate("MainWindow", "1e-15"))
        self.btnSearch.setText(_translate("MainWindow", "Search"))
        self.tabBox.setTabText(self.tabBox.indexOf(self.tabParameters), _translate("MainWindow", "Parameters"))
        self.lblResults.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Results:</span></p></body></html>"))
        self.btnClearLog.setText(_translate("MainWindow", "Clear log"))
        self.btnSearch2.setText(_translate("MainWindow", "Search"))
        self.btnPlot.setText(_translate("MainWindow", "Show plot"))
        self.tabBox.setTabText(self.tabBox.indexOf(self.tabResults), _translate("MainWindow", "Results"))

